/* Exact entries from the user's beast-wheel conversation; grouping is navigation, not biology or power. */
(function (root) {
  const groups = {
  "Mammal": [
    "Fox",
    "Red Fox",
    "White Fox",
    "Silver Fox",
    "Arctic Fox",
    "Fennec Fox",
    "Raccoon Dog",
    "Wolf",
    "Grey Wolf",
    "White Wolf",
    "Black Wolf",
    "Dhole",
    "Jackal",
    "Wild Dog",
    "Tiger",
    "White Tiger",
    "Black Tiger",
    "Golden Tiger",
    "Leopard",
    "Snow Leopard",
    "Clouded Leopard",
    "Panther",
    "Lynx",
    "Caracal",
    "Lion",
    "Bear",
    "Black Bear",
    "Brown Bear",
    "White Bear",
    "Panda",
    "Red Panda",
    "Weasel",
    "Stoat",
    "Ermine",
    "Ferret",
    "Mink",
    "Marten",
    "Sable",
    "Badger",
    "Honey Badger",
    "Otter",
    "River Otter",
    "Sea Otter",
    "Wolverine",
    "Civet",
    "Palm Civet",
    "Mongoose",
    "Genet",
    "Hedgehog",
    "Porcupine",
    "Pangolin",
    "Rat",
    "Mouse",
    "Field Mouse",
    "Dormouse",
    "Hamster",
    "Gerbil",
    "Vole",
    "Mole",
    "Shrew",
    "Squirrel",
    "Flying Squirrel",
    "Chipmunk",
    "Marmot",
    "Beaver",
    "Rabbit",
    "Hare",
    "White Hare",
    "Black Hare",
    "Deer",
    "White Deer",
    "Red Deer",
    "Sika Deer",
    "Roe Deer",
    "Musk Deer",
    "Reindeer",
    "Elk",
    "Moose",
    "Antelope",
    "Gazelle",
    "Saiga",
    "Ibex",
    "Mountain Goat",
    "Goat",
    "Ram",
    "Sheep",
    "Ox",
    "Bull",
    "Cow",
    "Water Buffalo",
    "Yak",
    "Bison",
    "Horse",
    "Wild Horse",
    "White Horse",
    "Black Horse",
    "Donkey",
    "Mule",
    "Zebra",
    "Wild Boar",
    "Pig",
    "Camel",
    "Elephant",
    "White Elephant",
    "Rhinoceros",
    "Monkey",
    "Macaque",
    "Golden Snub-Nosed Monkey",
    "Langur",
    "Gibbon",
    "Ape",
    "Bat",
    "Fruit Bat",
    "White Bat",
    "Vampire Bat",
    "Dog"
  ],
  "Bird": [
    "Crane",
    "Red-Crowned Crane",
    "White Crane",
    "Black Crane",
    "Heron",
    "Egret",
    "Bittern",
    "Stork",
    "Ibis",
    "Swan",
    "Goose",
    "Wild Goose",
    "Duck",
    "Mandarin Duck",
    "Eagle",
    "Golden Eagle",
    "Sea Eagle",
    "Serpent Eagle",
    "Hawk",
    "Goshawk",
    "Sparrowhawk",
    "Falcon",
    "Peregrine Falcon",
    "Kestrel",
    "Kite",
    "Harrier",
    "Owl",
    "Snowy Owl",
    "Horned Owl",
    "Barn Owl",
    "Raven",
    "Crow",
    "Magpie",
    "Jay",
    "Kingfisher",
    "Bee-Eater",
    "Hoopoe",
    "Swallow",
    "Swift",
    "Sparrow",
    "Lark",
    "Thrush",
    "Nightingale",
    "Oriole",
    "Starling",
    "Myna",
    "Wagtail",
    "Shrike",
    "Pheasant",
    "Golden Pheasant",
    "Silver Pheasant",
    "Peacock",
    "Peahen",
    "Quail",
    "Partridge",
    "Grouse",
    "Rooster",
    "Chicken",
    "Dove",
    "Pigeon",
    "Turtledove",
    "Parrot",
    "Parakeet",
    "Woodpecker",
    "Cuckoo",
    "Cormorant",
    "Pelican",
    "Gull",
    "Tern",
    "Albatross",
    "Petrel",
    "Frigatebird",
    "Flamingo"
  ],
  "Reptile": [
    "Snake",
    "White Snake",
    "Black Snake",
    "Golden Snake",
    "Green Snake",
    "Red Snake",
    "Python",
    "White Python",
    "Golden Python",
    "Black Python",
    "Cobra",
    "King Cobra",
    "White Cobra",
    "Viper",
    "Pit Viper",
    "Horned Viper",
    "Krait",
    "Coral Snake",
    "Rat Snake",
    "Grass Snake",
    "Water Snake",
    "Sea Snake",
    "Tree Snake",
    "Vine Snake",
    "Flying Snake",
    "Sand Snake",
    "Blind Snake",
    "Turtle",
    "Softshell Turtle",
    "Snapping Turtle",
    "Sea Turtle",
    "Tortoise",
    "Giant Tortoise",
    "Crocodile",
    "Alligator",
    "Gharial",
    "Monitor Lizard",
    "Water Monitor",
    "Komodo Dragon",
    "Gecko",
    "Tokay Gecko",
    "Skink",
    "Agama",
    "Iguana",
    "Chameleon",
    "Frilled Lizard",
    "Horned Lizard"
  ],
  "Amphibian": [
    "Frog",
    "Tree Frog",
    "Bullfrog",
    "Poison Frog",
    "Glass Frog",
    "Golden Frog",
    "Toad",
    "Cane Toad",
    "Horned Toad",
    "Salamander",
    "Giant Salamander",
    "Fire Salamander",
    "Newt",
    "Axolotl",
    "Caecilian"
  ],
  "Fish": [
    "Carp",
    "Golden Carp",
    "Black Carp",
    "White Carp",
    "Koi",
    "Goldfish",
    "Catfish",
    "Giant Catfish",
    "Eel",
    "Electric Eel",
    "Moray Eel",
    "Loach",
    "Sturgeon",
    "Paddlefish",
    "Salmon",
    "Trout",
    "Pike",
    "Perch",
    "Bass",
    "Arowana",
    "Golden Arowana",
    "Gourami",
    "Betta",
    "Tilapia",
    "Flying Fish",
    "Archerfish",
    "Mudskipper",
    "Pufferfish",
    "Porcupinefish",
    "Lionfish",
    "Stonefish",
    "Scorpionfish",
    "Anglerfish",
    "Lanternfish",
    "Swordfish",
    "Marlin",
    "Tuna",
    "Mackerel",
    "Seahorse",
    "Pipefish",
    "Sunfish",
    "Remora",
    "Shark",
    "White Shark",
    "Tiger Shark",
    "Bull Shark",
    "Hammerhead Shark",
    "Whale Shark",
    "Mako Shark",
    "Reef Shark",
    "Goblin Shark",
    "Thresher Shark",
    "Stingray",
    "Manta Ray",
    "Electric Ray",
    "Sawfish",
    "Skate"
  ],
  "Marine Beast": [
    "Dolphin",
    "River Dolphin",
    "White Dolphin",
    "Orca",
    "Whale",
    "Blue Whale",
    "Humpback Whale",
    "Sperm Whale",
    "Beluga",
    "Narwhal",
    "Seal",
    "Sea Lion",
    "Walrus",
    "Manatee",
    "Dugong"
  ],
  "Mollusk": [
    "Octopus",
    "Blue-Ringed Octopus",
    "Giant Octopus",
    "Dumbo Octopus",
    "Squid",
    "Giant Squid",
    "Firefly Squid",
    "Cuttlefish",
    "Nautilus",
    "Snail",
    "Land Snail",
    "Sea Snail",
    "Cone Snail",
    "Slug",
    "Sea Slug",
    "Nudibranch",
    "Abalone",
    "Limpet",
    "Clam",
    "Giant Clam",
    "Oyster",
    "Pearl Oyster",
    "Mussel",
    "Scallop"
  ],
  "Crustacean": [
    "Crab",
    "Red Crab",
    "Blue Crab",
    "Ghost Crab",
    "Fiddler Crab",
    "King Crab",
    "Spider Crab",
    "Hermit Crab",
    "Lobster",
    "Spiny Lobster",
    "Crayfish",
    "Shrimp",
    "Ghost Shrimp",
    "Pistol Shrimp",
    "Mantis Shrimp",
    "Krill",
    "Horseshoe Crab",
    "Barnacle"
  ],
  "Insect": [
    "Butterfly",
    "White Butterfly",
    "Black Butterfly",
    "Blue Butterfly",
    "Swallowtail Butterfly",
    "Monarch Butterfly",
    "Glasswing Butterfly",
    "Moth",
    "Luna Moth",
    "Silk Moth",
    "Atlas Moth",
    "Moon Moth",
    "Hawk Moth",
    "Death's-Head Moth",
    "Beetle",
    "Stag Beetle",
    "Rhinoceros Beetle",
    "Hercules Beetle",
    "Scarlet Beetle",
    "Jewel Beetle",
    "Golden Beetle",
    "Scarabaeus Beetle",
    "Dung Beetle",
    "Longhorn Beetle",
    "Tiger Beetle",
    "Ground Beetle",
    "Diving Beetle",
    "Fire-Colored Beetle",
    "Ladybird",
    "Cicada",
    "Golden Cicada",
    "Dragonfly",
    "Damselfly",
    "Praying Mantis",
    "Orchid Mantis",
    "Ghost Mantis",
    "Grasshopper",
    "Cricket",
    "Cave Cricket",
    "Locust",
    "Bee",
    "Honeybee",
    "Bumblebee",
    "Carpenter Bee",
    "Wasp",
    "Hornet",
    "Paper Wasp",
    "Mud Wasp",
    "Ant",
    "Black Ant",
    "Red Ant",
    "Army Ant",
    "Carpenter Ant",
    "Termite",
    "Firefly",
    "Glowworm",
    "Mayfly",
    "Lacewing",
    "Mosquito",
    "Horsefly",
    "Silkworm",
    "Caterpillar",
    "Stick Insect",
    "Leaf Insect"
  ],
  "Arachnid": [
    "Spider",
    "Orb-Weaver Spider",
    "Golden Orb-Weaver",
    "Wolf Spider",
    "Jumping Spider",
    "Huntsman Spider",
    "Trapdoor Spider",
    "Tarantula",
    "Black Widow",
    "Funnel-Web Spider",
    "Crab Spider",
    "Peacock Spider",
    "Scorpion",
    "Black Scorpion",
    "Golden Scorpion",
    "Emperor Scorpion",
    "Whip Scorpion",
    "Tailless Whip Scorpion",
    "Harvestman",
    "Tick",
    "Mite"
  ],
  "Myriapod": [
    "Centipede",
    "Giant Centipede",
    "Red-Headed Centipede",
    "Cave Centipede",
    "Waterfall Centipede",
    "Millipede",
    "Giant Millipede",
    "Pill Millipede",
    "Woodlouse",
    "Pill Bug"
  ],
  "Other Invertebrate": [
    "Jellyfish",
    "Moon Jellyfish",
    "Crystal Jellyfish",
    "Box Jellyfish",
    "Lion's Mane Jellyfish",
    "Comb Jelly",
    "Gooseberry Jellyfish",
    "Portuguese Man-of-War",
    "Sea Anemone",
    "Hydra",
    "Earthworm",
    "Leech",
    "Blood Leech",
    "Flatworm",
    "Ribbon Worm",
    "Velvet Worm",
    "Bristle Worm",
    "Fan Worm",
    "Bobbit Worm"
  ],
  "Deep-Sea / Unusual Heritage": [
    "Vampire Squid",
    "Glass Squid",
    "Giant Isopod",
    "Sea Spider",
    "Sea Angel",
    "Sea Butterfly",
    "Sea Cucumber",
    "Starfish",
    "Brittle Star",
    "Feather Star",
    "Sea Urchin",
    "Sand Dollar",
    "Lamprey",
    "Hagfish",
    "Coelacanth",
    "Oarfish",
    "Blobfish",
    "Dragonfish",
    "Viperfish",
    "Gulper Eel",
    "Fangtooth"
  ],
  "Mythic Beast": [
    "Dragon",
    "Azure Dragon",
    "White Dragon",
    "Black Dragon",
    "Golden Dragon",
    "Red Dragon",
    "Jiao Dragon",
    "Jiaolong",
    "Yinglong",
    "Winged Dragon",
    "Torch Dragon / Zhulong",
    "Dragon Turtle",
    "Qilin",
    "Fire Qilin",
    "Water Qilin",
    "Pixiu",
    "Xiezhi",
    "Bai Ze",
    "Suanni",
    "Nine-Tailed Fox",
    "Celestial Fox",
    "Fenghuang",
    "Luan Bird",
    "Vermilion Bird",
    "Three-Legged Crow",
    "Golden Crow",
    "Peng",
    "Kun",
    "Kunpeng",
    "Bi Fang",
    "Tengshe / Soaring Serpent",
    "Black Tortoise / Xuanwu",
    "White Tiger / Baihu",
    "Azure Dragon / Qinglong",
    "Vermilion Bird / Zhuque",
    "Dragon Horse / Longma",
    "Heavenly Horse / Tianma",
    "Moon Rabbit",
    "Jade Rabbit",
    "Qiongqi",
    "Taotie",
    "Taowu",
    "Hundun",
    "Dijiang",
    "Kui",
    "Zouwu",
    "Feilian",
    "Bashe / Great Snake",
    "Xiangliu",
    "Nian Beast"
  ]
};
  const api = { groups, source: 'https://chatgpt.com/c/6a9b3b58-0160-83e9-88d7-bfd32ef9276d', sourceTurn: 'dc7f0e23-fa60-4a3e-8b12-750613b79a3e' };
  root.BuilderHeritages = api;
  if (typeof module !== 'undefined') module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
