/* Original starting packages designed for this game, informed by genre sources.
   Quantities are house rules, not prices or grants copied from a novel. */
(function(root) {
  const item=(name,quantity=1,note='')=>({name,quantity,note});
  const travel=[item('Plain travel clothes'),item('Weather cloak'),item('Cloth shoulder pack'),item('Waterskin'),item('Bedroll'),item('Flint and tinder')];
  const make=(description,spiritStones,silverTaels,items)=>({description,spiritStones,silverTaels,items:[...travel,...items]});
  const packages={
    'Sect Disciple':make('A modest sect issue: dependable provisions, a little cultivation money, and recognizable sect belongings.',12,5,[item('Ration (one day)',7),item('Training sword'),item('Sect identity token'),item('Basic healing salve (dose)',2,'For treating ordinary cuts; no automatic Vitality restoration.'),item('Signal talisman',1,'A visible distress flare; does not guarantee assistance.'),item('Sect handbook',1,'Etiquette and local rules; grants no technique or access bonus.')]),
    'Rogue Cultivator':make('Limited savings, with durable tools for self-sufficient travel and gathering.',6,3,[item('Ration (one day)',10),item('Utility knife'),item('Hemp rope (10 metres)'),item('Herb-gathering sickle'),item('Empty medicine vial',3),item('Basic healing salve (dose)',1,'For treating ordinary cuts; no automatic Vitality restoration.'),item('Local trail map')]),
    'Clan Heir':make('Family wealth supplies the largest purse and finer belongings; the package grants no personal combat advantage.',30,15,[item('Ration (one day)',7),item('Fine steel sword',1,'Fine craftsmanship only; no stat or damage bonus.'),item('Spare formal robes'),item('Clan seal'),item('Basic healing salve (dose)',3,'For treating ordinary cuts; no automatic Vitality restoration.'),item('Signal talisman',2,'A visible distress flare; does not guarantee assistance.'),item('Family keepsake',1,'Choose its appearance; no hidden magical power.')]),
    'Wandering Doctor':make('A working healer carries sale proceeds, medical tools, and a larger stock of ordinary remedies.',8,8,[item('Ration (one day)',7),item('Utility knife'),item('Physician tool roll',1,'Needles, tweezers, small scissors and a mortar; no skill bonus.'),item('Clean bandage roll',6),item('Basic healing salve (dose)',6,'For treating ordinary cuts; no automatic Vitality restoration.'),item('Dried medicinal herb packet',4,'Ordinary herbs; does not grant alchemy or a guaranteed cure.'),item('Empty medicine vial',4),item('Herbal reference notebook')]),
    'Spirit Beast in Human Form':make('A newcomer to human society carries a small scavenged purse and things gathered from the wild.',3,1,[item('Ration (one day)',5),item('Walking staff'),item('Foraged herb packet',3,'Ordinary trade goods, not cultivation-boosting spirit herbs.'),item('Small polished stone',3,'Keepsakes or barter trinkets; not spirit stones.'),item('Keepsake from your former dwelling',1,'Personal significance only.')]),
    'Demonic Cultivator':make('A background of secretive practice supplies portable ritual materials and practical means of concealment. It does not force a cultivation-path choice.',8,3,[item('Ration (one day)',7),item('Ritual dagger',1,'Ordinary steel; no stat bonus or supernatural effect.'),item('Plain face covering'),item('Incense stick',10),item('Blank talisman paper',10,'Unenchanted; crafting requires rules learned separately.'),item('Ink and brush set'),item('Sealed ritual-material pouch',2,'Ordinary salt, ash and charcoal; no automatic technique.'),item('Basic healing salve (dose)',2,'For treating ordinary cuts; no automatic Vitality restoration.')]),
    'Mortal Scholar':make('Savings are in ordinary silver, with books and writing materials rather than spiritual treasures.',0,12,[item('Ration (one day)',7),item('Walking staff'),item('Ink and brush set'),item('Paper sheet',20),item('Bound notebook',2),item('Classical text'),item('Regional map'),item('Oil lantern'),item('Lamp oil flask',2)]),
    'Fallen Young Master':make('Most family wealth is gone. A few coins, worn finery and one keepsake remain.',4,6,[item('Ration (one day)',5),item('Worn steel sword',1,'Serviceable ordinary weapon; no penalty or bonus.'),item('Mended formal robes'),item('Tarnished family signet',1,'No guaranteed authority or market value.'),item('Basic healing salve (dose)',1,'For treating ordinary cuts; no automatic Vitality restoration.'),item('Old family letter',1,'A personal document, not an automatic entitlement.')])
  };
  const sources=[
    {title:'Wuxiaworld — General Glossary',url:'https://www.wuxiaworld.com/page/general-glossary-of-terms'},
    {title:"An Alchemist’s Path to Eternity, chapter 3",url:'https://www.wuxiaworld.com/novel/alchemists-path-to-eternity/apte-chapter-3'},
    {title:'Talisman Emperor, chapter 5',url:'https://www.wuxiaworld.com/novel/talisman-emperor/te-book-1-chapter-5'}
  ];
  const api={version:1,packages,sources};root.BuilderOrigins=api;
  if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
